const config = {
  bathrooms: [
    "arley",
    "bathrooms-to-love",
    "grohe",
    "just-trays",
    "mcalpine",
    "merlyn",
    "reflexion",
    "synergy",
    "trisen",
    "triton",
    "vema",
    "vitti",
  ],
  boilers: [],
  ceilings: ["multipanel"],
  doors: ["xl-joinery"],
  "electric-heating": [],
  "flooring-walls": ["multipanel", "palio-trade"],
  kitchens: [
    "aeg",
    "abode",
    "arley",
    "bosch",
    "electrolux",
    "elica",
    "grohe",
    "hotpoint",
    "insinkerator",
    "indesit",
    "mcalpine",
    "neff",
    "prima",
    "quooker",
    "teka",
    "trisen",
    "vitra",
    "whirlpool",
    "zanussi",
  ],
  lighting: ["bathrooms-to-love"],
  plumbing: ["arley", "grohe", "mcalpine", "synergy"],
  radiators: ["arley", "bathrooms-to-love", "synergy"],
  thermostats: ["tado"],
};

export default config;
