import { ColorsEnum } from "core/colors";

const LUCENTE_GLOSS = {
  price: { amount: 4444, currency: "GBP" },
  colors: [
    ColorsEnum.Anthracite,
    ColorsEnum.Cashmere,
    ColorsEnum.Cream,
    ColorsEnum.DustGrey,
    ColorsEnum.LightGrey,
    ColorsEnum.White,
  ],
  images: [
    "/kitchen-ranges/lucente-gloss/anthracite-1.jpg",
    "/kitchen-ranges/lucente-gloss/anthracite-2.jpg",
    "/kitchen-ranges/lucente-gloss/cashmere-1.jpg",
    "/kitchen-ranges/lucente-gloss/cashmere-2.jpg",
    "/kitchen-ranges/lucente-gloss/cream-1.jpg",
    "/kitchen-ranges/lucente-gloss/cream-2.jpg",
    "/kitchen-ranges/lucente-gloss/dust-grey-1.jpg",
    "/kitchen-ranges/lucente-gloss/dust-grey-2.jpg",
    "/kitchen-ranges/lucente-gloss/light-grey-1.jpg",
    "/kitchen-ranges/lucente-gloss/light-grey-2.jpg",
    "/kitchen-ranges/lucente-gloss/pavilion-1.jpg",
    "/kitchen-ranges/lucente-gloss/porcelain-1.jpg",
    "/kitchen-ranges/lucente-gloss/stone-1.jpg",
    "/kitchen-ranges/lucente-gloss/white-1.jpg",
    "/kitchen-ranges/lucente-gloss/white-2.jpg",
  ],
};

const LUCENTE_MATT = {
  price: { amount: 5555, currency: "GBP" },
  colors: [
    ColorsEnum.Anthracite,
    ColorsEnum.Cashmere,
    ColorsEnum.DustGrey,
    ColorsEnum.Indigo,
    ColorsEnum.LightGrey,
    ColorsEnum.White,
    ColorsEnum.PaintToOrder,
  ],
  images: [
    "/kitchen-ranges/lucente-matt/anthracite-1.jpg",
    "/kitchen-ranges/lucente-matt/anthracite-2.jpg",
    "/kitchen-ranges/lucente-matt/anthracite-3.jpg",
    "/kitchen-ranges/lucente-matt/anthracite-4.jpg",
    "/kitchen-ranges/lucente-matt/cashmere-1.jpg",
    "/kitchen-ranges/lucente-matt/cashmere-2.jpg",
    "/kitchen-ranges/lucente-matt/cashmere-3.jpg",
    "/kitchen-ranges/lucente-matt/cashmere-4.jpg",
    "/kitchen-ranges/lucente-matt/dust-grey-1.jpg",
    "/kitchen-ranges/lucente-matt/dust-grey-2.jpg",
    "/kitchen-ranges/lucente-matt/indigo-1.jpg",
    "/kitchen-ranges/lucente-matt/indigo-2.jpg",
    "/kitchen-ranges/lucente-matt/light-grey-1.jpg",
    "/kitchen-ranges/lucente-matt/light-grey-2.jpg",
    "/kitchen-ranges/lucente-matt/light-grey-3.jpg",
    "/kitchen-ranges/lucente-matt/light-grey-4.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-blue.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-brown-grey.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-cashmere.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-chalkstone.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-cream.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-dakar.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-denim.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-dust-grey.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-fjord.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-french-grey.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-ivory.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-lava.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-light-grey.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-mussel.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-olive.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-porcelain.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-sage-green.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-silver-grey.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-stone-grey.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-super-white.jpg",
    "/kitchen-ranges/lucente-matt/paint-to-order-white.jpg",
    "/kitchen-ranges/lucente-matt/stone-1.jpg",
    "/kitchen-ranges/lucente-matt/stone-2.jpg",
    "/kitchen-ranges/lucente-matt/stone-3.jpg",
    "/kitchen-ranges/lucente-matt/stone-4.jpg",
    "/kitchen-ranges/lucente-matt/white-1.jpg",
    "/kitchen-ranges/lucente-matt/white-2.jpg",
    "/kitchen-ranges/lucente-matt/white-3.jpg",
    "/kitchen-ranges/lucente-matt/white-4.jpg",
  ],
};

const VIVO_GLOSS = {
  price: { amount: 6666, currency: "GBP" },
  colors: [
    ColorsEnum.Anthracite,
    ColorsEnum.Cashmere,
    ColorsEnum.DustGrey,
    ColorsEnum.Ivory,
    ColorsEnum.LightGrey,
    ColorsEnum.White,
  ],
  images: [
    "/kitchen-ranges/vivo-gloss/anthracite-1.jpg",
    "/kitchen-ranges/vivo-gloss/anthracite-2.jpg",
    "/kitchen-ranges/vivo-gloss/cashmere-1.jpg",
    "/kitchen-ranges/vivo-gloss/dust-grey-1.jpg",
    "/kitchen-ranges/vivo-gloss/dust-grey-2.jpg",
    "/kitchen-ranges/vivo-gloss/ivory-1.jpg",
    "/kitchen-ranges/vivo-gloss/ivory-2.jpg",
    "/kitchen-ranges/vivo-gloss/light-grey-1.jpg",
    "/kitchen-ranges/vivo-gloss/light-grey-2.jpg",
    "/kitchen-ranges/vivo-gloss/porcelain-1.jpg",
    "/kitchen-ranges/vivo-gloss/porcelain-2.jpg",
    "/kitchen-ranges/vivo-gloss/porcelain-3.jpg",
    "/kitchen-ranges/vivo-gloss/porcelain-4.jpg",
    "/kitchen-ranges/vivo-gloss/stone-1.jpg",
    "/kitchen-ranges/vivo-gloss/stone-2.jpg",
    "/kitchen-ranges/vivo-gloss/white-1.jpg",
    "/kitchen-ranges/vivo-gloss/white-2.jpg",
  ],
};

const config = {
  "lucente-gloss": LUCENTE_GLOSS,
  "lucente-matt": LUCENTE_MATT,
  "vivo-gloss": VIVO_GLOSS,
};

export default config;
