#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint --fix ||
(
        echo '🥴 Next Lint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)
